language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pkchildrens/docker-react20 -f Dockerfile.dev .

script:
  - docker run -e CI=true pkchildrens/docker-react20 npm run test
